### ISSUE TITLE
Extracting w from stylegan2

### ISSUE THREAD

**Issue by imthebilliejoe** [gitlabspy/styleflow#2]
Hey there. Thank you for your amazing code. I'm trying to extract w from stylegan2 to use it in your code and I'm using this code:
`rnd = np.random.RandomState(seed)`
`z = rnd.randn(1, *Gs.input_shape[1:])`
`tflib.set_vars({var: rnd.randn(*var.shape.as_list()) for var in noise_vars})`
`w=Gs.components.mapping.run(z, None)`

but when i use w to generate image i get different results from using the initial z. I use this code to get them:
`image_from_z= Gs.run(z, None, **Gs_kwargs)`
`image_from_w=Gs.components.synthesis.run(w, **Gs_kwargs)`

How did you extract w?

thank you.

**Comment by gitlabspy** [comment]
Sorry for the late reply. For tensorflow 1.x, which I'm not quite familiar, I assume you need to build a graph to only undate/optimize w and  **_fix all noise ( on feature map)._**.  If you don't fix noise the results will remain some randomness and will be not easy to optimize.<br>
 I currently work on make a tensorflow 2 version of it, I'll try make it public asap.

**Comment by imthebilliejoe** [comment]
Hi there, thank you for your answer. 

In the end I solved the issue using the truncation trick in stylegan mixing (in the original repo of stylegan2) and I was able to obtain the proper ws (I dont know if you mean that).
Thanx
